### ISSUE TITLE
Keyboard shortcuts do not work.

### ISSUE THREAD

**Issue by MarioPeper** [GimelStudio/Gimel-Studio#20]
**Describe the bug**
Keyboard shortcuts Shift+A mostly work all other do not work.

**Steps to reproduce the bug**
Steps to reproduce the unexpected/unwanted behavior:
Just start Gimel Studio

**Expected behavior**
A clear and concise description of what you expected/wanted to happen.

**Application environment (IMPORTANT)**
- Application version: [ v0.5.0 beta]
- Launch method: [ launched from Blender addon and launched normally and launched from shell]

**System (please complete the following information):**
 - OS: [ Linux Ubuntu]
 - Version [20.04LTS]

**Additional context**
Add any other context and notes about the problem here.

**Comment by Correct-Syntax** [comment]
I have yet to figure out why this issue happens. It seems like it happens after the focus is lost for the node graph.
